version: 0.0
os: linux
files:
  - source: .
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh # install httpd, php....
      timeout: 300
      runas: root
    - location: scripts/before_install.sh # Xoa code cu
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh # Chmod 755, restart httpd
      timeout: 300
      runas: root
