name: Deploy to EC2

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # Dung OIDC (Role) nhu file moi cho bao mat
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
          aws-region: ap-northeast-1

      - name: Deploy to EC2 using CodeDeploy (Github Source)
        run: |
          # Lay ma dinh danh cua commit lan nay
          commit_hash=$(git rev-parse HEAD)

          # Ra lenh cho CodeDeploy lay code truc tiep tu Github
          aws deploy create-deployment \
            --application-name cicd-lab-app \
            --deployment-group-name cicd-lab-group \
            --github-location repository=${{ github.repository }},commitId=$commit_hash
